-- Script d'initialisation de la base de données RU'ya
-- Ce script ajoute des données de test pour le développement

-- Insertion d'utilisateurs de test (si la table USERS existe)
INSERT INTO USERS (ID_USER, USERNAME, EMAIL, PASSWORD, ROLE, CREATED_AT) 
VALUES (1, 'admin', 'admin@ruya.com', '$2a$10$rAM3nzX7K7VQ3X7K7VQ3X7K7VQ3X7K7VQ3X7K7VQ3X7K7VQ3X7K7VQ', 'ADMIN', SYSDATE)
ON DUPLICATE KEY UPDATE USERNAME = USERNAME;

INSERT INTO USERS (ID_USER, USERNAME, EMAIL, PASSWORD, ROLE, CREATED_AT) 
VALUES (2, 'user1', 'user1@ruya.com', '$2a$10$rAM3nzX7K7VQ3X7K7VQ3X7K7VQ3X7K7VQ3X7K7VQ3X7K7VQ3X7K7VQ', 'USER', SYSDATE)
ON DUPLICATE KEY UPDATE USERNAME = USERNAME;

-- Insertion de fichiers de test
INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (1, 1, 'Fichier_001.cheque', 'cheque', 'standard', '30', 'EN001', 'emis', 5000.00, 10, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (2, 1, 'Fichier_002.virement', 'virement', 'standard', '31', 'EN002', 'emis', 3000.00, 5, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (3, 2, 'Fichier_003.prelevement', 'prelevement', 'standard', '32', 'EN003', 'recu', 2000.00, 8, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (4, 2, 'Fichier_004.effet', 'effet', 'standard', '33', 'EN004', 'recu', 1500.00, 3, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (5, 1, 'Fichier_005.cheque', 'cheque', 'standard', '34', 'EN005', 'rendu', 7500.00, 15, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (6, 1, 'Fichier_006.virement', 'virement', 'standard', NULL, 'EN006', 'emis', 4000.00, 12, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (7, 2, 'Fichier_007.prelevement', 'prelevement', 'standard', NULL, 'EN007', 'recu', 1800.00, 7, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (8, 2, 'Fichier_008.effet', 'effet', 'standard', '30', 'EN008', 'emis', 2500.00, 6, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (9, 1, 'Fichier_009.cheque', 'cheque', 'standard', '31', 'EN009', 'emis', 6000.00, 20, SYSDATE, SYSDATE);

INSERT INTO FICHIERS (ID_FICHIER, ID_USER, NOM_FICHIER, TYPE_FICHIER, NATURE_FICHIER, CODE_VALEUR, COD_EN, SENS, MONTANT, NOMBER, CREATED_AT, UPDATED_AT) 
VALUES (10, 1, 'Fichier_010.virement', 'virement', 'standard', '32', 'EN010', 'recu', 3500.00, 9, SYSDATE, SYSDATE);

-- Commit des transactions
COMMIT; 